### ISSUE TITLE
'Log' was not declared in this scope

### ISSUE THREAD

**Issue by mikkelson** [robdobsn/ParticleRdJson#1]
I've imported RdJson directly using the Build IDE and all attempts to compile fail.

```n file included from lib/RdJson/src/RdJson.cpp:4:0:
lib/RdJson/src/RdJson.h: In static member function 'static jsmnrtok_t* RdJson::parseJson(const char*, int&, int)':
lib/RdJson/src/RdJson.h:179:13: error: 'Log' was not declared in this scope
             Log.error("RdJson: Source JSON is NULL");
             ^
lib/RdJson/src/RdJson.h:189:13: error: 'Log' was not declared in this scope
             Log.trace("RdJson: parseJson result %d maxTokens %d jsonLen %d", tokenCountRslt, maxTokens, strlen(jsonStr));
             ^
lib/RdJson/src/RdJson.h:204:13: error: 'Log' was not declared in this scope
             Log.info("parseJson result: %d", tokenCountRslt);
             ^
lib/RdJson/src/RdJson.h: In static member function 'static int RdJson::findObjectEnd(const char*, jsmnrtok_t*, unsigned int, int, int, bool)':
lib/RdJson/src/RdJson.h:284:17: error: 'Log' was not declared in this scope
                 Log.trace("findObjectEnd UNKNOWN!!!!!!! %d", pTok->type);
                 ^
make[1]: *** [../build/target/user/platform-10lib/RdJson/src/RdJson.o] Error 1
make: *** [user] Error 2```

**Comment by mikkelson** [comment]
This issue was caused by out of date firmware on the Electron (0.6.4, from 2016). After updating to 1.2.0, this issue was resolved.
